<?php
/**
 * Ultimate_Events extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Ultimate
 * @package        Ultimate_Events
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Events comments list template
 *
 * @category    Ultimate
 * @package     Ultimate_Events
 * @author      Ultimate Module Creator
 */
?>
<?php $_events = $this->getEvents()?>
<?php if ($_events->getAllowComments()) : ?>
    <?php $_comments = $this->getComments(); ?>
    <?php if (count($_comments)) : ?>
        <div class="box-collateral box-reviews" id="events-reviews">
            <h2><?php echo $this->__('Comments for: %s', $_events->getTitle()) ?></h2>
            <?php echo $this->getPagerHtml() ?>
            <dl>
                <?php foreach ($_comments as $_comment):?>
                <dt>
                    <div class="author"><?php echo $this->__('On %s %s wrote:', $this->formatDate($_comment->getCreatedAt(), 'long'), $this->htmlEscape($_comment->getName()))?></div>
                    <strong><?php echo $this->htmlEscape($_comment->getTitle()) ?></strong>
                </dt>
                <dd>
                    <?php echo nl2br($this->htmlEscape($_comment->getComment())) ?>
                </dd>
                <?php endforeach; ?>
            </dl>
            <?php echo $this->getPagerHtml() ?>
        </div>
    <?php endif;?>
    <?php echo $this->getChildHtml('comment_form') ?>
<?php endif;?>
