<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLogin
 * @copyright   Copyright (c) 2014 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<?php if (!Mage::getStoreConfig('onestepcheckout/general/enabled')) { ?>
<?php echo $this->getChildHtml('login_before') ?>
<div class="<?php if (!$this->helper('customer')->isRegistrationAllowed() && !$this->getQuote()->isAllowedGuestCheckout()) echo ' login-only' ?> pslogin-form">
    <div class="col-xs-12 col-md-offset-3 col-md-6">
        
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <?php if (Mage::helper('pslogin')->modulePositionEnabled('login') && Mage::helper('pslogin')->hasButtons()) : ?>
            <?php echo $this->getChildHtml('pslogin_buttons'); ?>
        <?php endif; ?>
        <h2 class="text-center"><?php echo $this->__('Sign in to speed up your checkout process') ?></h2>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
        <div class="">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <ul class="form-list">
                <li>
                    <div class="form-group">
                        <input placeholder="<?php echo $this->__('Email Address') ?>" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" class="form-control required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
                    </div>
                    <div class="form-group">
                        <input placeholder="<?php echo $this->__('Password') ?>" type="password" class="form-control validate-password required-entry" id="login-password" name="login[password]" />
                    </div>
                    <button type="submit" class="btn btn-block btn-primary" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
                </li>
                <li>
                    <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="text-center"><?php echo $this->__('Forgot your password?') ?></a>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
            <input name="context" type="hidden" value="checkout" />
        </div>
        </form>
        
    </div>
    <div class="col-xs-12 col-md-offset-3 col-md-6">
        <hr/>
        <h2>
            <?php if ( $this->getQuote()->isAllowedGuestCheckout() && $this->helper('customer')->isRegistrationAllowed() ): ?>
                <?php echo $this->__('Checkout as a Guest or Register') ?>
            <?php elseif ( $this->getQuote()->isAllowedGuestCheckout() && !$this->helper('customer')->isRegistrationAllowed() ): ?>
                <?php echo $this->__('Checkout as a Guest') ?>
            <?php else: ?>
                <?php echo $this->__('Register to Create an Account') ?>
            <?php endif; ?>
        </h2>
        <?php if ( !$this->getQuote()->isAllowedGuestCheckout() && $this->helper('customer')->isRegistrationAllowed() ): ?>
            <p class="description"><?php echo $this->__('Register and save time!') ?></strong><br />
                <?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul>
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
        <?php elseif ( $this->getQuote()->isAllowedGuestCheckout() && $this->helper('customer')->isRegistrationAllowed() ): ?>
            <p class="description"><?php echo $this->__('Register with us for future convenience:') ?></p>
        <?php endif ?>
        <?php if ( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <ul class="form-list">
                <?php if ( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <li class="control">
                    <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if ($this->getQuote()->getCheckoutMethod()!=Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
                </li>
                <?php endif; ?>
                <?php if ( $this->helper('customer')->isRegistrationAllowed() ): ?>
                <li class="control">
                    <input type="radio" name="checkout_method" id="login:register" value="register"<?php if ($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" />
                    <label for="login:register"><?php echo $this->__('Register and Checkout') ?></label>
                </li>
                <?php endif; ?>
            </ul>
        <?php else: ?>
            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
        <?php endif; ?>
            <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
                <button id="onepage-guest-register-button" type="button" class="btn btn-primary btn-block" onclick="checkout.setMethod();"><span><span><?php echo $this->__('Continue') ?></span></span></button>
            <?php elseif ($this->helper('checkout')->isCustomerMustBeLogged()): ?>
                <button id="onepage-guest-register-button" type="button" class="btn btn-default btn-block" onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'"><span><span><?php echo $this->__('Register') ?></span></span></button>
            <?php else: ?>
                <form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
                    <button id="onepage-guest-register-button" type="submit" class="btn btn-default btn-block"><span><span><?php echo $this->__('Register') ?></span></span></button>
                </form>
            <?php endif; ?>
    </div>
    
</div>

<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if (loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
<?php
    $registerParam = $this->getRequest()->getParam('register');
    if ($registerParam || $registerParam === ''):
?>
    <script type="text/javascript">
    //<![CDATA[
        document.observe("dom:loaded", function() {
            if ($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
    //]]>
    </script>
<?php endif; ?>
<?php } else {
    echo $this->setTemplate('onestepcheckout/onepage/login.phtml')->toHtml();
}
