<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLogin
 * @copyright   Copyright (c) 2014 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<div class="col-sm-offset-2 col-sm-8 account-create pslogin-form">
    
    
    <?php echo $this->getChildHtml('form_fields_before')?>
    
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" class="form-register col-sm-offset-2 col-sm-8 scaffold-form" enctype="multipart/form-data">
        <?php if (Mage::helper('pslogin')->modulePositionEnabled('register') && Mage::helper('pslogin')->hasButtons()) : ?>
            <?php echo $this->getChildHtml('pslogin_buttons'); ?>
        <?php endif; ?>
        <h2><?php echo $this->__('Or create an account') ?></h2>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <div class="form-group">
            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
        </div>
        <div class="form-group">
            <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="required-entry form-control required" placeholder="Email"/>
        </div>
        <div class="form-group">
            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="required-entry form-control validate-password required" placeholder="<?php echo $this->__('Password') ?>"/>
        </div>
        <div class="form-group">
             <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="required-entry form-control validate-cpassword required" placeholder="<?php echo $this->__('Confirm Password') ?>"/>
        </div>
        <?php echo $this->getChildHtml('form.additional.info'); ?>
        <?php if ($this->isNewsletterEnabled()): ?>
            <div class='form-group'>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if ($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> />
                        <?php echo $this->__('Sign Up for Newsletter') ?>
                    </label>
                </div>
            </div>
        <?php endif ?>
        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        <div class="form-group">
            <button type="submit" title="<?php echo $this->__('Register') ?>" class="btn btn-primary"><?php echo $this->__('Register') ?></button>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if ($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
</div>
