<?php
$className = Mage::getConfig()->getBlockClassName('custommenu/custommenu');
            $block = new $className();  
 $_menu = $block->renderCategoriesMenuHtml(0,'level-top') ?>
<?php if($_menu): ?>
<?php endif ?>

<?php $_categories = Mage::helper('catalog/category')->getStoreCategories() ?>
<?php if(count($_categories)): 
    ?>
<div class="nav-container">
        <div id="pt_custommenu" class="pt_custommenu">
        <?php
        $showhome = Mage::getStoreConfig('custommenu/general/showhome');
        $active = '';
        if(Mage::getSingleton('cms/page')->getIdentifier() == 'fashion3_home'  && Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms') :
            $active = ' act';
        endif; 
        if($showhome){
            $id     = "_home";
            $html[] = '<div id="pt_menu' . $id . '" class="pt_menu' . $active . '">';
            $html[] = '<div class="parentMenu">';
            $html[] = '<a href="'.Mage::helper('core/url')->getHomeUrl().'">';
            $html[] = '<span>Home</span>';
            $html[] = '</a>';
            $html[] = '</div>';
//            $html[] = '<div id="popup' . $id . '" class="popup" style="display: none; width: 1228px;">';
//            $html[] = '</div>';
            $html[] = '</div>';
            $html = implode("\n", $html);
            echo $html;
        }
        $className = Mage::getConfig()->getBlockClassName('custommenu/custommenu');
        $block = new $className();               
        //$block->_prepareData();
        $item = 0;
        foreach ($_categories as $_category): $item++;?>
            <?php echo $block->drawCustomMenuItem($_category,0,false,$item) ?>
        <?php endforeach ?>
        <?php
        $collection = Mage::getModel('cms/block')->getCollection()
                    ->addFieldToFilter('identifier', array('like'=>'pt_item_menu'.'%'))
                    ->addFieldToFilter('is_active', 1);
        foreach($collection as $key => $value){
            $blockId = $value->getIdentifier();
            $blockHtml = $this->getLayout()->createBlock('cms/block')->setBlockId($blockId)->toHtml();
            if ($blockHtml) echo $block->drawCustomMenuBlock($blockId);
        }
        
        /*menu links*/
        $blockLinkId = 'pt_menu_links';
        $blockLinkHtml = $this->getLayout()->createBlock('cms/block')->setBlockId($blockLinkId)->toHtml();
        if ($blockLinkHtml){
            $id     = "_link";
            $htmlLink[] = '<div id="pt_menu' . $id . '" class="pt_menu">';
            $htmlLink[] = '<div class="parentMenu">';
            $htmlLink[] = $blockLinkHtml;
            $htmlLink[] = '</div>';
            $htmlLink[] = '</div>';
            $htmlLink = implode("\n", $htmlLink);
            echo $htmlLink;
        }
        ?>
        <div class="pt_menu nav-10 pt_menu_no_child">
            <div class="parentMenu">
                <a href="/sobre">
                    <span><?php echo $this->__('A Godê') ?></label></span>
                </a>
            </div>
        </div>
        <div class="pt_menu nav-10 pt_menu_no_child">
            <div class="parentMenu">
                <a href="/blog">
                    <span>Blog</span>
                </a>
            </div>
        </div>
        <div class="pt_menu nav-10 pt_menu_no_child">
            <div class="parentMenu">
                <a href="/events">
                    <span><?php echo $this->__('Agenda') ?></label></span>
                </a>
            </div>
        </div>
        <div class ="navbar-right-wrapper">
            <div class="slogan">
              <span><?php echo $this->__('Arte que Inspira') ?></span>
            </div>
            <div class='social-icons-navbar pull-right'>
                <div class="pt_menu nav-10 pt_menu_no_child">
                    <div class="parentMenu">
                        <a class='social' target="_blank" href="http://instagram.com/godegaleriaonline">
                            <i class="fab fa-instagram"></i>
                        </a>
                    </div>
                </div>
                <div class="pt_menu nav-10 pt_menu_no_child">
                    <div class="parentMenu">
                        <a class='social' target="_blank" href="http://facebook.com/godegaleriaonline">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearBoth"></div>
    </div>
</div>
<script type="text/javascript">
    function toggleSidenav(bool) {
      document.body.classList.toggle('sidenav-active');  
      document.body.classList.toggle('noscroll');
    }
</script>
<script type="text/javascript">
//<![CDATA[
var CUSTOMMENU_POPUP_EFFECT = <?php echo (int)Mage::getStoreConfig('custommenu/popup/effect')?>;
var CUSTOMMENU_POPUP_TOP_OFFSET = <?php echo (int)Mage::getStoreConfig('custommenu/popup/top_offset')?>;
//]]>
</script>

<?php endif ?>
